# Generated by Django 5.2.1 on 2025-05-10 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={},
        ),
        migrations.RemoveField(
            model_name='venda',
            name='data',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade_atendimentos',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='valor',
        ),
        migrations.AddField(
            model_name='venda',
            name='contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_atendimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('A VISTA', 'A VISTA'), ('A VISTA COM TROCA', 'A VISTA COM TROCA'), ('FINANCIAMENTO', 'FINANCIAMENTO'), ('FINANCIAMENTO COM TROCA', 'FINANCIAMENTO COM TROCA'), ('SEM INFORMAÇÃO', 'SEM INFORMAÇÃO')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='modelo_interesse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='origem',
            field=models.CharField(blank=True, choices=[('LOJA', 'LOJA'), ('VENDEDOR', 'VENDEDOR'), ('CHATBOT', 'CHATBOT'), ('COCKPIT', 'COCKPIT'), ('INSTAGRAM', 'INSTAGRAM'), ('MONTEIRO', 'MONTEIRO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(blank=True, choices=[('VENDIDO', 'VENDIDO'), ('EM NEGOCIAÇÃO', 'EM NEGOCIAÇÃO'), ('RECUSA DE CRÉDITO', 'RECUSA DE CRÉDITO'), ('NEGOCIAÇÃO ENCERRADA', 'NEGOCIAÇÃO ENCERRADA')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
